import type { Metadata } from "next";
import { Inika } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inika = Inika({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zero-Context",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inika.className}>
        {children}
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
